import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler
import config


# ----- label generation -------------------------------------------------------

def label_trades(
    signals: pd.Series,
    spread:  pd.Series,
    zscore:  pd.Series,
) -> pd.DataFrame:
    """
    For each trade entry generated by the primary model, simulate the trade
    forward to its natural exit (mean reversion) or stop-loss, and label it:
      1 = trade was profitable (spread reverted in our favor)
      0 = trade was a loss     (spread diverged or hit stop)

    This is the core of Lopez de Prado's Meta-Labeling framework.
    The primary model (cointegration z-score) generates candidate signals;
    the secondary model (Random Forest) learns which of those signals
    are likely to succeed given the market context at entry.

    Returns a DataFrame indexed by entry date with columns:
      label, entry_z, exit_z, trade_direction, holding_days
    """
    records = []
    in_trade = False
    entry_date = None
    entry_z = None
    direction = 0

    for date, sig in signals.items():
        z = zscore.get(date, np.nan)
        if np.isnan(z):
            continue

        if not in_trade and sig != 0:
            # trade entry
            in_trade   = True
            entry_date = date
            entry_z    = z
            direction  = sig

        elif in_trade and sig == 0:
            # trade closed — label it
            exit_z = z

            # for a long trade (direction=+1), we entered when z was very negative
            # and profit means z reverted upward (exit_z > entry_z)
            # for a short trade (direction=-1), we entered when z was very positive
            # and profit means z reverted downward (exit_z < entry_z)
            if direction == 1:
                label = 1 if exit_z > entry_z else 0
            else:
                label = 1 if exit_z < entry_z else 0

            holding = (date - entry_date).days

            records.append({
                "entry_date":      entry_date,
                "label":           label,
                "entry_z":         entry_z,
                "exit_z":          exit_z,
                "trade_direction": direction,
                "holding_days":    holding,
            })

            in_trade = False

    if not records:
        return pd.DataFrame()

    df = pd.DataFrame(records).set_index("entry_date")
    return df


# ----- feature engineering ----------------------------------------------------

def build_features(
    entry_dates: pd.DatetimeIndex,
    zscore:      pd.Series,
    spread:      pd.Series,
    vix:         pd.Series,
    prices_y:    pd.Series,
    prices_x:    pd.Series,
    vol_window:  int = 20,
    pair_id:     str = None,
) -> pd.DataFrame:
    """
    Constructs the feature vector at each trade entry date.

    Features are chosen to capture market context that the primary z-score
    signal cannot encode on its own:

    1. z_at_entry        — magnitude of z-score at entry
                           (extreme entries may be more reliable)
    2. spread_volatility — rolling std of spread returns
                           (high vol periods may have wider mis-pricing)
    3. z_velocity        — first difference of z-score (rate of change)
                           (a rapidly moving z-score may overshoot)
    4. z_acceleration    — second difference of z-score
                           (is the z-score still diverging or starting to turn?)
    5. vix_level         — CBOE VIX at entry
                           (high VIX = stressed market, mean reversion may fail)
    6. vix_percentile    — rolling 252-day percentile rank of VIX
                           (relative regime measure, more stable than raw VIX)
    7. ou_half_life      — recent Ornstein-Uhlenbeck half-life over 60 days
                           (is the pair still actively mean-reverting?)
    8. volume_ratio      — ratio of rolling volume Y / rolling volume X
                           (liquidity imbalance may predict spread behavior)

    All features are point-in-time (no lookahead): we only use data
    available on or before the entry date.
    """
    # precompute rolling quantities on the full series
    spread_returns  = spread.pct_change()
    spread_vol      = spread_returns.rolling(vol_window).std()
    z_velocity      = zscore.diff(1)
    z_acceleration  = zscore.diff(2)
    vix_pctile      = vix.rolling(252).rank(pct=True)

    features = {}

    for date in entry_dates:
        if date not in zscore.index:
            continue

        z   = zscore.get(date, np.nan)
        svol = spread_vol.get(date, np.nan)
        zvel = z_velocity.get(date, np.nan)
        zacc = z_acceleration.get(date, np.nan)
        vix_val = vix.get(date, np.nan)
        vix_pct = vix_pctile.get(date, np.nan)

        # OU half-life over the last 60 days ending at entry
        try:
            idx = spread.index.get_loc(date)
            recent_spread = spread.iloc[max(0, idx - 60): idx]
            if len(recent_spread) >= 20:
                from research.pairs_finder import compute_half_life
                hl = compute_half_life(recent_spread)
            else:
                hl = np.nan
        except Exception:
            hl = np.nan

        features[date] = {
            "z_at_entry":        z,
            "spread_volatility": svol,
            "z_velocity":        zvel,
            "z_acceleration":    zacc,
            "vix_level":         vix_val,
            "vix_percentile":    vix_pct,
            "ou_half_life":      hl if not np.isinf(hl) else np.nan,
        }

    feat_df = pd.DataFrame(features).T
    feat_df.index = pd.to_datetime(feat_df.index)

    # one-hot encode pair_id so the model generalizes across pairs
    # while retaining pair-specific information
    if pair_id is not None:
        feat_df["pair_id"] = pair_id
        pair_dummies = pd.get_dummies(feat_df["pair_id"], prefix="pair")
        feat_df = pd.concat([feat_df.drop(columns=["pair_id"]), pair_dummies], axis=1)

    return feat_df


# ----- walk-forward ML training -----------------------------------------------

class MetaLabeler:
    """
    Walk-forward Random Forest classifier for trade filtering and sizing.

    Architecture:
      - The primary model (cointegration z-score) generates a binary signal.
      - This model takes that signal as a candidate and outputs P(success).
      - Only trades where P(success) > ML_PROB_THRESHOLD are executed.
      - Position size is scaled proportionally to P(success):
            size = signal * (P - threshold) / (1 - threshold)

    Walk-forward methodology:
      - At each retraining step T, train on all labeled trades in [0, T).
      - Generate probability estimates only for trades in [T, T + step).
      - Roll forward by WALK_FORWARD_STEP days.
      - This ensures the model is never trained on future information.

    Model choice — Random Forest:
      - Handles non-linear interactions between features
      - Robust to outliers (trees are not sensitive to scale)
      - Shallow depth (MAX_DEPTH=4) limits overfitting on small samples
      - Probability outputs are well-calibrated without Platt scaling
        at this depth
    """

    def __init__(self):
        self.models: list[RandomForestClassifier] = []
        self.scalers: list[StandardScaler] = []
        self.oos_auc: list[float] = []

    def _build_model(self) -> RandomForestClassifier:
        return RandomForestClassifier(
            n_estimators     = config.RF_N_ESTIMATORS,
            max_depth        = config.RF_MAX_DEPTH,
            min_samples_leaf = config.RF_MIN_SAMPLES_LEAF,
            class_weight     = "balanced",  # compensates for label imbalance
            random_state     = 42,
        )

    def walk_forward_predict(
        self,
        features:  pd.DataFrame,
        labels:    pd.Series,
    ) -> pd.Series:
        """
        Runs walk-forward cross-validation and returns out-of-sample
        predicted probabilities for every trade.

        Returns a Series indexed by trade entry date, values in [0, 1].
        """
        features = features.dropna()
        labels   = labels.reindex(features.index).dropna()
        features = features.reindex(labels.index)

        if len(labels) < config.ML_MIN_TRAIN_SAMPLES:
            # not enough history to train reliably — return neutral probability
            return pd.Series(0.5, index=labels.index)

        probabilities = pd.Series(np.nan, index=labels.index)
        dates = labels.index.sort_values()
        step  = config.WALK_FORWARD_STEP

        period = 0
        while True:
            train_end_idx = config.ML_MIN_TRAIN_SAMPLES + period * step

            if train_end_idx >= len(dates):
                break

            train_dates = dates[:train_end_idx]
            test_start  = train_end_idx
            test_end    = min(train_end_idx + step, len(dates))
            test_dates  = dates[test_start:test_end]

            if len(test_dates) == 0:
                break

            X_train = features.loc[train_dates].values
            y_train = labels.loc[train_dates].values
            X_test  = features.loc[test_dates].values
            y_test  = labels.loc[test_dates].values

            # scale features — RF is invariant to scale, but standardizing
            # makes the OU half-life and VIX features comparable in magnitude
            scaler = StandardScaler()
            X_train = scaler.fit_transform(X_train)
            X_test  = scaler.transform(X_test)

            model = self._build_model()
            model.fit(X_train, y_train)

            probs = model.predict_proba(X_test)[:, 1]
            probabilities.loc[test_dates] = probs

            # track out-of-sample AUC per period
            if len(np.unique(y_test)) > 1:
                auc = roc_auc_score(y_test, probs)
                self.oos_auc.append(auc)
                print(f"  walk-forward period {period + 1}: "
                      f"train={len(train_dates)} trades, "
                      f"test={len(test_dates)} trades, "
                      f"OOS AUC={auc:.3f}")

            self.models.append(model)
            self.scalers.append(scaler)
            period += 1

        return probabilities.dropna()

    def apply_filter_and_size(
        self,
        primary_signals: pd.Series,
        probabilities:   pd.Series,
    ) -> pd.Series:
        """
        Converts primary {-1, 0, 1} signals into probability-scaled positions.

        If P(success) < ML_PROB_THRESHOLD: position = 0 (do not trade)
        If P(success) >= threshold:
            scaled_size = (P - threshold) / (1 - threshold)
            final position = signal * scaled_size  (range: 0 to 1)

        This means a trade with P=0.60 at threshold=0.60 gets size=0.0,
        and a trade with P=0.85 gets size=0.417. Only high-conviction
        signals are executed at material size.
        """
        scaled = pd.Series(0.0, index=primary_signals.index)

        for date, sig in primary_signals.items():
            if sig == 0:
                continue
            if date not in probabilities.index:
                # no ML prediction available — skip trade
                continue

            p = probabilities[date]
            thresh = config.ML_PROB_THRESHOLD

            if p < thresh:
                scaled[date] = 0.0
            else:
                size = (p - thresh) / (1.0 - thresh)
                scaled[date] = sig * size

        return scaled
